name: maven-package
version: '3.8.6'
summary: mvn 3.8.6
description: |
  https://github.com/ozkanpakdil/snap-maven
  Source https://maven.apache.org/download.cgi
    
grade: stable
confinement: classic

parts:
  mvn:
    plugin: dump
    source: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
    build-packages:
      - software-properties-common
apps:
  test-geekbench4:
    command: mvn
