name: maven-package
version: '3.8.6'
summary: mvn 3.8.6
description: |
  https://github.com/ozkanpakdil/snap-maven
  Source https://maven.apache.org/download.cgi
    
grade: stable
confinement: classic

base: bare
build-base: core18

parts:
  maven:
    plugin: dump
    source: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
    source-subdir: bin/
    filesets:
      bin: [ usr/bin/* ]
    stage:
      - $bin
    build-packages:
      - software-properties-common
apps:
  mvn:
    command: bin/mvn
