name: maven
version: '3.8.6'
summary: mvn 3.8.6
description: |
  https://github.com/ozkanpakdil/snap-maven
  Source https://maven.apache.org/download.cgi
    
grade: stable
confinement: classic

parts:
  mvn:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      tar -xvf apache-maven-3.8.6-bin.tar.gz
      mv apache-maven-3.8.6 /opt/
      echo "M2_HOME=/opt/apache-maven-3.8.6
      PATH=$M2_HOME/bin:$PATH
      export PATH
      " >> ~/.bashrc
